### ISSUE TITLE
I want this for Sandstorm!

### ISSUE THREAD

**Issue by neynah** [stephane-rolland/brio#1]
I would totally use this... @mquandalle :)

**Comment by mquandalle** [comment]
ahah I started evangelizing Sandstorm but the 24h of the hackathon was a bit short :-)

We need to remove some hacks we (I) added in the last few commits and implement a few more small features and then I will be more than happy to support Brio on Sandstorm. From [Kenton meeting notes](https://groups.google.com/forum/#!topic/sandstorm-dev/fIpJvTEcOIg) I see that you have done your office hours during this week-end, but I would love if you could design a Brio icon (and logo?) for Sandstorm once you have some time or inspiration :-)

**Comment by neynah** [comment]
I'd be happy to! :) I'll probably start it in a week or so. Have any input?

**Comment by camelaissani** [comment]
@mquandalle @stephane-rolland @krischamp how we can continue on this project? Should I create a board on http://try.wekan.io ?

**Comment by mquandalle** [comment]
try.wekan.io is hosted on the free Meteor hosting that is way too slow to be usable unfortunatly. Let’s use Sandstorm, here is a board: https://alpha.sandstorm.io/grain/fYhpZ8ANNtQzo2dZLsTEbX. I have sent you an edit link by email.

**Comment by mquandalle** [comment]
@neynah Currently our primary UI element is [the flashcard](https://github.com/stephane-rolland/brio/blob/117d2db60e9f1bbb0d6ffe3be14afb7808ae87af/public/imgs/card-example.png). So one possibility would be to use the love face labeled “Brio” and put it in the letter O of Brio. Or maybe other have some ideas?

**Comment by camelaissani** [comment]
:( no more idea for the logo

**Comment by stephane-rolland** [comment]
By the end of the week, I plan to to buy a vps on ovh or 1&1, for one year.
Hopefully brio.io will be available publicly.

**Comment by mquandalle** [comment]
@stephane-rolland, brio.io [is already registered](http://www.who.is/whois/brio.io/).

Let’s keep this issue about Sandstorm packaging and feel free to open an issue for anything else.

**Comment by stephane-rolland** [comment]
I think the problem is about where the knowledge of users go (the comments for example)... and we have no discussed about that. 

I'm pro " License Common Creative", as it is on Stackoverflow or Wikipedia.
But that should be discussed between us.

**Comment by krischamp** [comment]
@all
as this name (brio.io) is taken, I would suggest "withBrio.io" ...

**Comment by neynah** [comment]
Here's a mock-up of what the @mquandalle's idea would look like. I'm stuck on ideas at the moment but I'll see if I can think of anything over the weekend.
![brio-logo-draft1](https://cloud.githubusercontent.com/assets/855341/10677924/0fecdaf0-78c4-11e5-9f9b-37d042b19e7e.png)

**Comment by neynah** [comment]
@mquandalle How's the app coming along? :D
